add_test( [==[Data Access Factory - Create Engine]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Factory - Create Engine]==]  )
set_tests_properties( [==[Data Access Factory - Create Engine]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Factory - Create XML Processor]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Factory - Create XML Processor]==]  )
set_tests_properties( [==[Data Access Factory - Create XML Processor]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Factory - Create ZIP Processor]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Factory - Create ZIP Processor]==]  )
set_tests_properties( [==[Data Access Factory - Create ZIP Processor]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Project Info - Validation]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Project Info - Validation]==]  )
set_tests_properties( [==[Project Info - Validation]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Track Info - Validation]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Track Info - Validation]==]  )
set_tests_properties( [==[Track Info - Validation]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Clip Info - Validation]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Clip Info - Validation]==]  )
set_tests_properties( [==[Clip Info - Validation]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Validation Result - Operations]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Validation Result - Operations]==]  )
set_tests_properties( [==[Validation Result - Operations]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Result Template - Success Case]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Result Template - Success Case]==]  )
set_tests_properties( [==[Result Template - Success Case]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Result Template - Error Case]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Result Template - Error Case]==]  )
set_tests_properties( [==[Result Template - Error Case]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Archive Entry - Validation]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Archive Entry - Validation]==]  )
set_tests_properties( [==[Archive Entry - Validation]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[XML Document - Helper Methods]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[XML Document - Helper Methods]==]  )
set_tests_properties( [==[XML Document - Helper Methods]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Load Project Info]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Load Project Info]==]  )
set_tests_properties( [==[Data Access Engine - Load Project Info]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Load Tracks]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Load Tracks]==]  )
set_tests_properties( [==[Data Access Engine - Load Tracks]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Load Clips]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Load Clips]==]  )
set_tests_properties( [==[Data Access Engine - Load Clips]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Validate File]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Validate File]==]  )
set_tests_properties( [==[Data Access Engine - Validate File]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Is Valid Project File]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Is Valid Project File]==]  )
set_tests_properties( [==[Data Access Engine - Is Valid Project File]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Create Reader]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Create Reader]==]  )
set_tests_properties( [==[Data Access Engine - Create Reader]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[Data Access Engine - Create Writer]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[Data Access Engine - Create Writer]==]  )
set_tests_properties( [==[Data Access Engine - Create Writer]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[XML Processor - Load Document]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[XML Processor - Load Document]==]  )
set_tests_properties( [==[XML Processor - Load Document]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[XML Processor - Parse Document]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[XML Processor - Parse Document]==]  )
set_tests_properties( [==[XML Processor - Parse Document]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[ZIP Processor - List Entries]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[ZIP Processor - List Entries]==]  )
set_tests_properties( [==[ZIP Processor - List Entries]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[ZIP Processor - Extract Entry]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[ZIP Processor - Extract Entry]==]  )
set_tests_properties( [==[ZIP Processor - Extract Entry]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
add_test( [==[ZIP Processor - Is Valid Archive]==] D:/Repos/dawproject_c/05-implementation/build_ci/Debug/test_data_red.exe [==[ZIP Processor - Is Valid Archive]==]  )
set_tests_properties( [==[ZIP Processor - Is Valid Archive]==] PROPERTIES WORKING_DIRECTORY D:/Repos/dawproject_c/05-implementation/build_ci)
set( test_data_red_TESTS [==[Data Access Factory - Create Engine]==] [==[Data Access Factory - Create XML Processor]==] [==[Data Access Factory - Create ZIP Processor]==] [==[Project Info - Validation]==] [==[Track Info - Validation]==] [==[Clip Info - Validation]==] [==[Validation Result - Operations]==] [==[Result Template - Success Case]==] [==[Result Template - Error Case]==] [==[Archive Entry - Validation]==] [==[XML Document - Helper Methods]==] [==[Data Access Engine - Load Project Info]==] [==[Data Access Engine - Load Tracks]==] [==[Data Access Engine - Load Clips]==] [==[Data Access Engine - Validate File]==] [==[Data Access Engine - Is Valid Project File]==] [==[Data Access Engine - Create Reader]==] [==[Data Access Engine - Create Writer]==] [==[XML Processor - Load Document]==] [==[XML Processor - Parse Document]==] [==[ZIP Processor - List Entries]==] [==[ZIP Processor - Extract Entry]==] [==[ZIP Processor - Is Valid Archive]==])
